SMS_Broadcaster Website/Controllers/SMPP_SettingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SMS_Broadcaster_Website.Models;
using SMS_Broadcaster_Website.Controllers;

namespace SMS_Broadcaster_Website
{
    [Authorize]
    public class SMPP_SettingsController : Controller
    {
        private Forest_InteractiveEntities db = new Forest_InteractiveEntities();
        private Broadcast_MessagesController the_controller = new Broadcast_MessagesController();

        // GET: SMPP_Settings
        public async Task<ActionResult> Index()
        {
 
            return View(await db.SMPP_Settings.ToListAsync());
        }

        // GET: SMPP_Settings/Details/5
        public async Task<ActionResult> Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SMPP_Settings SMPP_Settings = await db.SMPP_Settings.FindAsync(id);
            if (SMPP_Settings == null)
            {
                return HttpNotFound();
            }
            return View(SMPP_Settings);
        }

        // GET: SMPP_Settings/Create
        public ActionResult Create()
        {
 
            return View();
        }

        // POST: SMPP_Settings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Settings_ID,System_id,Password,System_type,Hostname,Port,Source_Address_TON,Source_Address_NPI,Destination_Address_TON,Destination_Address_NPI")] SMPP_Settings sMPP_Settings)
        {
            if (ModelState.IsValid)
            {
                db.SMPP_Settings.Add(sMPP_Settings);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sMPP_Settings);
        }

        // GET: SMPP_Settings/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SMPP_Settings sMPP_Settings = await db.SMPP_Settings.FindAsync(id);
            if (sMPP_Settings == null)
            {
                return HttpNotFound();
            }
            return View(sMPP_Settings);
        }

        // POST: SMPP_Settings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Settings_ID,System_id,Password,System_type,Hostname,Port,Source_Address_TON,Source_Address_NPI,Destination_Address_TON,Destination_Address_NPI")] SMPP_Settings sMPP_Settings)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sMPP_Settings).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sMPP_Settings);
        }

        // GET: SMPP_Settings/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SMPP_Settings sMPP_Settings = await db.SMPP_Settings.FindAsync(id);
            if (sMPP_Settings == null)
            {
                return HttpNotFound();
            }
            return View(sMPP_Settings);
        }

        // POST: SMPP_Settings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
 
            SMPP_Settings sMPP_Settings = await db.SMPP_Settings.FindAsync(id);
            db.SMPP_Settings.Remove(sMPP_Settings);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SMS_Broadcaster Website/Views/Shared/_Layout.cshtml
@using SMS_Broadcaster_Website.Models
@{ 
    List<BroadcastMessagerDashboard> messages_pending = ViewData["list_pending"] as List<SMS_Broadcaster_Website.Models.BroadcastMessagerDashboard>;
    List<BroadcastMessagerDashboard> messages_accepted = ViewData["list_accepted"] as List<SMS_Broadcaster_Website.Models.BroadcastMessagerDashboard>;
    List<BroadcastMessagerDashboard> messages_rejected = ViewData["list_rejected"] as List<SMS_Broadcaster_Website.Models.BroadcastMessagerDashboard>;
    Boolean authenticated = Convert.ToBoolean(ViewData["authenticated"]);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SMPP Tester</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/bundles/bootstrap-datetimepicker")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    @Html.ActionLink("SMPP Tester", "Dashboard", "Broadcast_Messages", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Statistics<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Summary", "Dashboard", "Broadcast_Messages")</li>
                            <li>@Html.ActionLink("All Messages", "Full_Statistics", "Broadcast_Messages")</li>
                            @if(true)
                            {
                              <li>@Html.ActionLink("Accepted Messages", "Accepted_Statistics", "Broadcast_Messages")</li>
                            }
                            
                            @if(true)
                            {
                              <li>@Html.ActionLink("Pending Messages", "Pending_Statistics", "Broadcast_Messages")</li>
                            }
                            
                            @if (true)
                            {
                                <li>@Html.ActionLink("Rejected Messages", "Rejected_Statistics", "Broadcast_Messages")</li>
                            }
                            
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Messages", "Index", "Broadcast_Messages")</li>
                    <li>@Html.ActionLink("Settings", "Index", "SMPP_Settings")</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br/>
           @Html.Partial("_Notifications")
           @RenderBody()
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Forest Interactive - SMPP Tester</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>

SMS_Broadcaster Website/Views/Shared/_Notifications.cshtml
@using SMS_Broadcaster_Website.Extensions

@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
<!-- display errors -->
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(errorList.Count() > 1){
            <strong><span class="glyphicon glyphicon-remove"></span> There are @errorList.Count() errors: </strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-remove"></span> Error: </strong>
            @Html.Raw(errorList.First())
        }
    </div>
}

<!-- display warnings -->
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(warningList.Count() > 1){
            <strong><span class="glyphicon glyphicon-warning-sign"></span> There are @warningList.Count() warnings: </strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-warning-sign"></span> Warning: </strong>
            @Html.Raw(warningList.First())
        }
    </div>
}

<!-- display success -->
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(successList.Count() > 1){
            <strong><span class="glyphicon glyphicon-ok"></span> There are @successList.Count() successful notifications: </strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-ok"> </strong>
            @Html.Raw(successList.First())
        }
    </div>
}

<!-- display success -->
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(infoList.Count() > 1){
            <strong><span class="glyphicon glyphicon-info-sign"></span> There are @infoList.Count() notifications: </strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-info-sign"></span> </strong>
            @Html.Raw(infoList.First())
        }
    </div>
}