SMS_Broadcaster Website/Models/Broadcast_Messages.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Broadcaster_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broadcast_Messages
    {
        public int ID { get; set; }
        public string Source_Addr { get; set; }
        public string Destination_Addr { get; set; }
        public string Data_Type { get; set; }
        public string Message_ID { get; set; }
        public string Text { get; set; }
        public string Submit_Mode { get; set; }
        public System.DateTime Date_Time_Send { get; set; }
        public System.DateTime Date_Time_Created { get; set; }
        public System.DateTime Date_Time_Edited { get; set; }
        public string Sent { get; set; }
        public string Submitted { get; set; }
        public Nullable<int> Settings_ID { get; set; }
    }
}

SMS_Broadcaster Website/Controllers/Broadcast_MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SMS_Broadcaster_Website.Models;
using SMS_Broadcaster_Website.Extensions;
using System.Data.Entity.Validation;
using System.Diagnostics;
using PagedList.EntityFramework;
using System.IO;

namespace SMS_Broadcaster_Website.Controllers
{
    [Authorize]
    public class Broadcast_MessagesController : Controller
    {

        private Forest_InteractiveEntities db = new Forest_InteractiveEntities();

        // GET: Dashboard
        public async Task<ActionResult> Dashboard(int? page)
        {
            Set_Up();
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var contact_group = (from messages in db.Broadcast_Messages select messages)
                                .OrderBy(message => message.Date_Time_Send)
                                .GroupBy(message => message.Destination_Addr)
                                .Select(group => new BroadcastMessagerDashboard
                                {
                                    Destination_Addr = group.Key,
                                    Count = group.Count()
                                }).Take(10);

            contact_group = contact_group.OrderBy(message => message.Destination_Addr);

            var setting_group_pending = (from messages in db.Broadcast_Messages select messages)
                                 .Where(message => message.Date_Time_Send > DateTime.Now)
                                 .GroupBy(message => message.Settings_ID)
                                 .Select(group => new BroadcastMessagerDashboardSettings
                                 {
                                     Settings_ID = (int)group.Key,
                                     Count = group.Count()
                                 })
                                 .Take(10)
                                 .ToArray();

            var setting_group_accepted = (from messages in db.Broadcast_Messages select messages)
                               .Where(message => message.Sent == "true")
                               .GroupBy(message => message.Settings_ID)
                               .Select(group => new BroadcastMessagerDashboardSettings
                               {
                                   Settings_ID = (int)group.Key,
                                   Count = group.Count()
                               })
                               .Take(10)
                               .ToArray();

            var setting_group_rejected = (from messages in db.Broadcast_Messages select messages)
                                .Where(message => message.Sent != "true" && (message.Date_Time_Send < DateTime.Now))
                                .GroupBy(message => message.Settings_ID)
                                .Select(group => new BroadcastMessagerDashboardSettings
                                {
                                    Settings_ID = (int)group.Key,
                                    Count = group.Count()
                                })
                                .Take(10)
                                .ToArray();

            ViewData["setting_group_accepted"] = setting_group_accepted.ToList();
            ViewData["setting_group_rejected"] = setting_group_rejected.ToList();
            ViewData["setting_group_pending"] = setting_group_pending.ToList();

            return View(await contact_group.ToPagedListAsync(pageNumber, pageSize));

        }

        public async Task<ActionResult> Full_Statistics(int? page, string startDate, string endDate, string type = "")
        {
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            DateTime start = Convert.ToDateTime(startDate);
            DateTime end = Convert.ToDateTime(endDate);

            var contact_group_temp = from messages in db.Broadcast_Messages select messages;

            if (!string.IsNullOrEmpty(startDate) && !string.IsNullOrEmpty(endDate))
            {
                contact_group_temp = contact_group_temp.Where(m => m.Date_Time_Send >= start)
                                                       .Where(m => m.Date_Time_Send <= end);
            }

            contact_group_temp = contact_group_temp.OrderBy(message => message.Date_Time_Send);

            var contact_group = contact_group_temp
                                 .GroupBy(message => message.Destination_Addr)
                                 .Select(group => new BroadcastMessagerDashboard
                                 {
                                     Destination_Addr = group.Key,
                                     Count = group.Count(),
                                 });

            contact_group = contact_group.OrderBy(message => message.Destination_Addr);

            return View(await contact_group.ToPagedListAsync(pageNumber, pageSize));
        }

        public async Task<ActionResult> Accepted_Statistics(int? page, string startDate, string endDate, string type = "")
        {
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            DateTime start = Convert.ToDateTime(startDate);
            DateTime end = Convert.ToDateTime(endDate);

            var list_accepted_temp = from messages in db.Broadcast_Messages select messages;

            if (!string.IsNullOrEmpty(startDate) && !string.IsNullOrEmpty(endDate))
            {
                list_accepted_temp = list_accepted_temp.Where(m => m.Date_Time_Send >= start)
                                                       .Where(m => m.Date_Time_Send <= end);
            }

            var list_accepted = list_accepted_temp
                                .Where(message => message.Sent == "true")
                                .GroupBy(message => message.Destination_Addr)
                                .Select(group => new BroadcastMessagerDashboard
                                {
                                   Destination_Addr = group.Key,
                                   Count = group.Count()
                                });

            list_accepted = list_accepted.OrderBy(message => message.Destination_Addr);

            return View(await list_accepted.ToPagedListAsync(pageNumber, pageSize));
        }

        public async Task<ActionResult> Pending_Statistics(int? page, string startDate, string endDate, string type = "")
        {
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            DateTime start = Convert.ToDateTime(startDate);
            DateTime end = Convert.ToDateTime(endDate);

            var list_pending_temp = from messages in db.Broadcast_Messages select messages;

            if (!string.IsNullOrEmpty(startDate) && !string.IsNullOrEmpty(endDate))
            {
                list_pending_temp = list_pending_temp.Where(m => m.Date_Time_Send >= start)
                                                     .Where(m => m.Date_Time_Send <= end);
            }

            var list_pending = list_pending_temp
                               .Where(message => message.Date_Time_Send > DateTime.Now)
                               .GroupBy(message => message.Destination_Addr)
                               .Select(group => new BroadcastMessagerDashboard
                               {
                                  Destination_Addr = group.Key,
                                  Count = group.Count()
                               });

            /*var list_pending = (from messages in db.Broadcast_Messages select messages)
                                .Where(message => message.Date_Time_Send > DateTime.Now)
                                .GroupBy(message => message.Destination_Addr)
                                .Select(group => new BroadcastMessagerDashboard
                                {
                                    Destination_Addr = group.Key,
                                    Count = group.Count()
                                });
            */

            list_pending = list_pending.OrderBy(message => message.Destination_Addr);

            return View(await list_pending.ToPagedListAsync(pageNumber, pageSize));
        }

        public async Task<ActionResult> Rejected_Statistics(int? page, string startDate, string endDate, string type = "")
        {
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            DateTime start = Convert.ToDateTime(startDate);
            DateTime end = Convert.ToDateTime(endDate);

            var list_rejected_temp = from messages in db.Broadcast_Messages select messages;

            if (!string.IsNullOrEmpty(startDate) && !string.IsNullOrEmpty(endDate))
            {
                list_rejected_temp = list_rejected_temp.Where(m => m.Date_Time_Send >= start)
                                                       .Where(m => m.Date_Time_Send <= end);
            }

            var list_rejected = list_rejected_temp.Where(message => message.Sent != "true"
                                                            && (message.Date_Time_Send < DateTime.Now))
                                                  .GroupBy(message => message.Destination_Addr)
                                                  .Select(group => new BroadcastMessagerDashboard
                                                  {
                                                    Destination_Addr = group.Key,
                                                    Count = group.Count()
                                                  });
            /*
            var list_rejected = (from messages in db.Broadcast_Messages select messages)
                   .Where(message => message.Sent != "true"

SMS_Broadcaster Website/Views/Broadcast_Messages/Accepted_Statistics.cshtml
@model PagedList.IPagedList<SMS_Broadcaster_Website.Models.BroadcastMessagerDashboard>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Accepted";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>Accepted Statistics <small>SMS Messages</small></h1>
</div>

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">Search</div>
        <div class="panel-body">

            @using (Html.BeginForm())
            {
                <p>
                    <div class="row top-buffer bottom-buffer">
                        <div class="col-md-4">
                            <div class="input-group  start-date">
                                <span class="input-group-addon">Start Date</span>
                                @Html.TextBox("startDate", "", new { @class = "form-control datetimepicker_start" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="input-group start-date">
                                <span class="input-group-addon ">End Date</span>
                                @Html.TextBox("endDate", "", new { @class = "form-control datetimepicker_end" })
                            </div>

                        </div>
                    </div>
                    <div class="pull-left">
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </div>
                </p>
            }
        </div>
    </div>

    <table class="table table-striped table-bordered">
        <tr>
            <th>
                Destination Address
            </th>
            <th>
                Count
            </th>
        </tr>

        @foreach (var message in Model)
        {
            <tr>
                <td>
                    @message.Destination_Addr
                </td>
                <td>
                    @message.Count
                </td>
            </tr>
        }
    </table>
</div>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 1 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Accept_Statistics", new { page }))
<script type="text/javascript">
    $(function () {
        $('.datetimepicker_start').datetimepicker({
                format:"DD-MM-YYYY HH:mm"
        });

        $('.datetimepicker_end').datetimepicker({
            format:"DD-MM-YYYY HH:mm",
        });

        $(".datetimepicker_start").on("dp.change", function (e) {
            $('.datetimepicker_end').data("DateTimePicker").minDate(e.date);
        });

        $(".datetimepicker_end").on("dp.change", function (e) {
            $('.datetimepicker_start').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>

SMS_Broadcaster Website/Views/Broadcast_Messages/Create.cshtml
@model SMS_Broadcaster_Website.Models.Broadcast_Messages

@{
    ViewBag.Title = "Create";
}

<div class="page-header">
    <h1>Create <small>SMS Messages</small></h1>
</div>

@using (Html.BeginForm("Create", "Broadcast_Messages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("Date_Time_Created", DateTime.Now)
    @Html.Hidden("Date_Time_Edited", DateTime.Now)
    @Html.Hidden("Message_ID","")
    @Html.Hidden("Sent","false")
    @Html.Hidden("Submitted", "false")
    @Html.Hidden("Destination_Addr","")
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Source_Addr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Source_Addr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Source_Addr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination_Addr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="contact_file" />
            </div>
        </div>

        <div class="form-group">
            @{
                List<SelectListItem> list_DataCoding = new List<SelectListItem>();
                list_DataCoding.Add(new SelectListItem
                {
                    Text = "Default",
                    Value = "Default"
                });
                list_DataCoding.Add(new SelectListItem
                {
                    Text = "Latin1",
                    Value = "Latin1"
                });
                list_DataCoding.Add(new SelectListItem
                {
                    Text = "Octet Unspecified",
                    Value = "OctetUnspecified"
                });
                list_DataCoding.Add(new SelectListItem
                {
                    Text = "Unicode 2",
                    Value = "UCS2"
                });
                list_DataCoding.Add(new SelectListItem
                {
                    Text = "Unicode Flash SMS",
                    Value = "UnicodeFlashSMS"
                });
                list_DataCoding.Add(new SelectListItem
                {
                    Text = "Default Flash SMS",
                    Value = "DefaultFlashSMS"
                });
            }
            @Html.LabelFor(model => model.Data_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Data_Type, list_DataCoding )
                @Html.ValidationMessageFor(model => model.Data_Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" }, cols = "80", rows = "5" })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @{ 
                List<SelectListItem> list_SubmitMode = new List<SelectListItem>();
                list_SubmitMode.Add(new SelectListItem
                {
                    Text = "Short Message",
                    Value = "ShortMessage"
                });
                list_SubmitMode.Add(new SelectListItem
                {
                    Text = "Payload",
                    Value = "Payload" 
                });
            }
            @Html.LabelFor(model => model.Submit_Mode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Submit_Mode, list_SubmitMode)
                @Html.ValidationMessageFor(model => model.Submit_Mode, "", new { @class = "text-danger" })
            </div>
            
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Time_Send, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ Html.EnableClientValidation(false); }
                @Html.TextBoxFor(model => model.Date_Time_Send, new { @class = "form-control datetimepicker no-client-validation", placeholder = "date and time" })
                @Html.ValidationMessageFor(model => model.Date_Time_Send, "", new { @class = "text-danger" })
                @{ Html.EnableClientValidation(true); }
                <script type="text/javascript">
                $(function () {
                    $('.datetimepicker').datetimepicker({
                        format:"DD-MM-YYYY HH:mm"
                    });
                });
                </script>
            </div>
        </div>

        @*<div class="form-group">
        @Html.LabelFor(model => model.Date_Time_Created, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Time_Created, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date_Time_Created, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date_Time_Edited, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Time_Edited, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date_Time_Edited, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sent, "", new { @class = "text-danger" })
            </div>
        </div>
        *@
        @{ 
            List<SelectListItem> list_settings = ViewData["List_Settings_ID"] as List<SelectListItem>;
        }
        
    <div class="form-group">
        @Html.LabelFor(model => model.Settings_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Settings_ID, list_settings)
            @Html.ValidationMessageFor(model => model.Settings_ID, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/fixes")
}

SMS_Broadcaster Website/Views/Broadcast_Messages/Delete.cshtml
@model SMS_Broadcaster_Website.Models.Broadcast_Messages

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Broadcast_Messages</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Source_Addr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Source_Addr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination_Addr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination_Addr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Submit_Mode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Submit_Mode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Time_Send)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Time_Send)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Time_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Time_Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Time_Edited)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Time_Edited)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Settings_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Settings_ID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SMS_Broadcaster Website/Views/Broadcast_Messages/Index.cshtml
@model PagedList.IPagedList<SMS_Broadcaster_Website.Models.Broadcast_Messages>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="page-header pull-left">
        <h1>Index <small>SMS Messages</small></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Search</div>
            <div class="panel-body">

                @using (Html.BeginForm())
            {
                    <p>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                        Destination / MessageID
                                    </span>
                                    @Html.TextBox("SearchString", "", new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        
                        <div class="row top-buffer bottom-buffer">
                            <div class="col-md-4">
                                <div class="input-group  start-date">
                                    <span class="input-group-addon">Start Date</span>
                                    @Html.TextBox("startDate", "", new { @class = "form-control datetimepicker_start" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="input-group start-date">
                                    <span class="input-group-addon ">End Date</span>
                                    @Html.TextBox("endDate", "", new { @class = "form-control datetimepicker_end" })
                                </div>

                            </div>
                        </div>
                        <div class="pull-left">
                            <input type="submit" value="Search" class="btn btn-primary" />
                        </div>
                    </p>
                }
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            Source Address
                        </th>
                        <th>
                            @Html.ActionLink("Destination", "Index", new { sortOder = ViewBag.DestinationSortParam })
                        </th>
                        <th>
                            Text
                        </th>
                        <th>
                            Submit Type
                        </th>
                        <th>
                            Data Encoding
                        </th>
                        <th>
                            @Html.ActionLink("Date & Time To Send", "Index", new { sortOrder = ViewBag.DateSortParam })
                        </th>
                        <th>
                            Submitted
                        </th>
                        <th>
                            Sent
                        </th>
                        <th>
                            Message ID
                        </th>

                        <th>
                            Date Time Created
                        </th>
                        <th>
                            Date Time Edited
                        </th>
                        <th>
                            Settings ID
                        </th>
                        <th>

                        </th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Source_Addr)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Destination_Addr)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Text)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Submit_Mode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data_Type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date_Time_Send)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Submitted)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sent)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Message_ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date_Time_Created)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date_Time_Edited)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Settings_ID)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) <br />
                                @Html.ActionLink("Details", "Details", new { id = item.ID }) <br />
                                @Html.ActionLink("Delete", "Delete", new { id = item.ID })<br />
                            </td>
                        </tr>
                    </tbody>
                }

            </table>
        </div>
        <p>
            @Html.ActionLink("Create New", "Create", "Broadcast_Messages", "", new { @class = "btn btn-primary pull-right" })
        </p>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('.datetimepicker_start').datetimepicker({
                format:"DD-MM-YYYY HH:mm"
        });

        $('.datetimepicker_end').datetimepicker({
            format:"DD-MM-YYYY HH:mm",
        });

        $(".datetimepicker_start").on("dp.change", function (e) {
            $('.datetimepicker_end').data("DateTimePicker").minDate(e.date);
        });

        $(".datetimepicker_end").on("dp.change", function (e) {
            $('.datetimepicker_start').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>

<br />